CREATE TABLE grids
(
    id BIGINTEGER NOT NULL PRIMARY KEY,
    c1 INTEGER NOT NULL,
    c2 INTEGER NOT NULL,
    c3 INTEGER NOT NULL,
    c4 INTEGER NOT NULL,
    c5 INTEGER NOT NULL,
    c6 INTEGER NOT NULL,
    c7 INTEGER NOT NULL,
    c8 INTEGER NOT NULL,
    c9 INTEGER NOT NULL
);

CREATE INDEX ON grids(c1);
CREATE INDEX ON grids(c2);
CREATE INDEX ON grids(c3);
CREATE INDEX ON grids(c4);
CREATE INDEX ON grids(c5);
CREATE INDEX ON grids(c6);
CREATE INDEX ON grids(c7);
CREATE INDEX ON grids(c8);
CREATE INDEX ON grids(c9);

CREATE TABLE positions
(
    id SERIAL PRIMARY KEY,
    g BIGINTEGER REFERENCES grids(id),
    h1 BIGINTEGER REFERENCES grids(id),
    h2 BIGINTEGER REFERENCES grids(id),
    v1 BIGINTEGER REFERENCES grids(id),
    v2 BIGINTEGER REFERENCES grids(id)
);