CREATE TABLE grids
(
    id BIGINTEGER NOT NULL PRIMARY KEY,
    c1 INTEGER NOT NULL,
    c2 INTEGER NOT NULL,
    c3 INTEGER NOT NULL,
    c4 INTEGER NOT NULL,
    c5 INTEGER NOT NULL,
    c6 INTEGER NOT NULL,
    c7 INTEGER NOT NULL,
    c8 INTEGER NOT NULL,
    c9 INTEGER NOT NULL
);

CREATE INDEX ON grids(c1);
CREATE INDEX ON grids(c2);
CREATE INDEX ON grids(c3);
CREATE INDEX ON grids(c4);
CREATE INDEX ON grids(c5);
CREATE INDEX ON grids(c6);
CREATE INDEX ON grids(c7);
CREATE INDEX ON grids(c8);
CREATE INDEX ON grids(c9);

CREATE TABLE boards
(
    id SERIAL PRIMARY KEY,
    g1 BIGINTEGER NOT NULL REFERENCES grids(id),
    g2 BIGINTEGER NOT NULL REFERENCES grids(id),
    g3 BIGINTEGER NOT NULL REFERENCES grids(id),
    g4 BIGINTEGER NOT NULL REFERENCES grids(id),
    g5 BIGINTEGER NOT NULL REFERENCES grids(id),
    g6 BIGINTEGER NOT NULL REFERENCES grids(id),
    g7 BIGINTEGER NOT NULL REFERENCES grids(id),
    g8 BIGINTEGER NOT NULL REFERENCES grids(id),
    g9 BIGINTEGER NOT NULL REFERENCES grids(id)
);